language: python

python:
  - 3.5
  - 3.6

env:
  global:
    # Disable tests that hit external servers
    - BUNDLE_REPOS_TESTS_SKIP_EXTERNAL=1

before_install:
- dpkg-query -l git

install:
- git config --global user.email travis@git-multi-bundler.mike10004.travis-ci.org
- git config --global user.name "Travis Building mike10004/git-multi-bundler"

script:
- python3 -m unittest discover
